### ISSUE TITLE
File Updates

### ISSUE THREAD

**Issue by rasogi** [jjssoftware/asustor-dropbox#7] opened 2021-08-19 18:34 UTC
Hi!

I've been using your script which was working fine. However, I noticed after some time that updating the files is not working. For example, I uploaded the test.txt file yesterday, today I edited it and added new information to this file. But in today's sync, the task returns me the following error:

b'testing text.docx' exists with different stats, downloading
Total elapsed time for download: 0.964
12952 bytes; md: FileMetadata(client_modified=datetime.datetime(2021, 8, 19, 14, 47, 6), content_hash='f657eb8d6f92d8dfb612716aa37be5dfa8ebff5a97847181fb8bb993dff3f736', export_info=NO_DE_SET, haslock='AA file_licit_NOT_SET, haslockdown='AA filename_explic_NOT_SET, =True, media_info=NOT_SET, name='testing text.docx', parent_shared_folder_id=NOT_SET, path_display='/dropbox_data/folder1/testing text.docx', path_lower='/dropbox_data/folder1/testing text.docx', property_groups= NOT_SET, rev='015c9eaab22890d0000000223f88340', server_modified=datetime.datetime(2021, 8, 19, 14, 50, 14), sharing_info=NOT_SET, size=12952, symlink_info=NOT_SET)
Process terminated early due to exception

Because of this, any changes made to files locally are not synced to the dropbox.
What can I do to fix this situation?

**Comment by bebo-dot-dev** [comment] 2021-08-22 08:57
Not sure tbh, I've just run a similar test here and it worked as expected:

1. Created a new text file in a `$SOURCE_FOLDER` directory, a file that contains nothing more than "hello world" text
2. Ran the script in full sync mode: `python $PYTHON_DROPBOX_SCRIPT --token $DROPBOX_AUTH_TOKEN -y -ih -s ~/test $SOURCE_FOLDER`
3. Verified the text file was uploaded to dropbox
4. Edited the file created in (1) so that it now contains "hello world edited" text
5. Ran the script once again in full sync mode
6. Verified the edited file was uploaded to dropbox

Seems to work here.

The message you included in your report doesn't describe the actual cause of the failure unfortunately. Are there any more details in your log file?

**Comment by rasogi** [comment] 2021-08-23 12:00
I've just run the same test again for more details. Here's the output:


root@AS6510T-0D17:/volume1/.@plugins/AppCentral/community-dropbox-sync/log # cat 20210823.115002455046.log
23/08/2021 08:50:02 INFO Process started
23/08/2021 08:50:41 ERROR

23/08/2021 08:50:41 ERROR Caught unhandled exception
Traceback (most recent call last):
  File "/usr/local/AppCentral/community-dropbox-sync/bin/updown.py", line 743, in <module>
    main()
  File "/usr/local/AppCentral/community-dropbox-sync/bin/updown.py", line 93, in main
    upload_result = traverse_local_folders(dbx, local_sync_folder, dropbox_folder, args)
  File "/usr/local/AppCentral/community-dropbox-sync/bin/updown.py", line 189, in traverse_local_folders
    data = f.read()
  File "/usr/local/AppCentral/python3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 14: invalid continuation byte
23/08/2021 08:50:41 INFO Runtime: 0 days 0 hours 0 mins 39 secs
23/08/2021 08:50:41 INFO process aborted with: Process terminated early due to exception

I did some tests in another environment and just like you said, the script works fine.

**Comment by bebo-dot-dev** [comment] 2021-08-25 06:38
Your last reply suggests you're using python 3, if so I'm surprised that it got as far as it did because python 3 has never been tested (by me) and is not supported by this script. Perhaps this is the cause of your problem, my suggestion is you try to use python 2.7.x

**Comment by rasogi** [comment] 2021-08-30 20:49
I've tried python 2.7 in the beggining, but I just couldn't install lockfile with pip.  I finally managed to install the module after installing pip3 and thats the reason I tried python 3. This is the error I get when I try using python 2.7:

Traceback (most recent call last):
  File "updown.py", line 16, in <module>
    import lockfile
ImportError: No module named lockfile

An then, after trying to install lockfile: 

root@AS6510T-0D17:/volume1/home/it # cat /root/.pip/pip.log
/usr/local/bin/pip run on Mon Aug 30 17:44:29 2021
Downloading/unpacking lockfile

  Getting page https://pypi.python.org/simple/lockfile/
  Could not fetch URL https://pypi.python.org/simple/lockfile/: HTTP Error 403: SNI is required
  Will skip URL https://pypi.python.org/simple/lockfile/ when looking for download links for lockfile
  Getting page https://pypi.python.org/simple/
  Could not fetch URL https://pypi.python.org/simple/: HTTP Error 403: SNI is required
  Will skip URL https://pypi.python.org/simple/ when looking for download links for lockfile
  Cannot fetch index base URL https://pypi.python.org/simple/

  URLs to search for versions for lockfile:
  * https://pypi.python.org/simple/lockfile/
  Getting page https://pypi.python.org/simple/lockfile/
  Could not fetch URL https://pypi.python.org/simple/lockfile/: HTTP Error 403: SNI is required
  Will skip URL https://pypi.python.org/simple/lockfile/ when looking for download links for lockfile
  Could not find any downloads that satisfy the requirement lockfile

Cleaning up...

  Removing temporary dir /tmp/pip_build_root...
No distributions at all found for lockfile

Exception information:
Traceback (most recent call last):
  File "/usr/local/AppCentral/python/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/usr/local/AppCentral/python/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/AppCentral/python/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1085, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/local/AppCentral/python/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/index.py", line 265, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for lockfile

**Comment by bebo-dot-dev** [comment] 2021-08-30 21:26
https://pypi.org/project/lockfile/ 

It does exist.

What you're seeing looks like some sort of environmental issue unrelated to this project and I can't support whatever the cause of that is.  

The bottom line is if you do want to use the [python script](https://github.com/bebo-dot-dev/asustor-dropbox/blob/master/bin/updown.py) that is included in this repo, you will need python 2.7.x to run and failing that, you'll have to work through fixing whatever needs fixing to get it working with python 3 yourself.

**Comment by rasogi** [comment] 2021-08-31 13:22
I understand. I would like to thank you for your willingness and time. I will try to solve this problem with python 3 anyway.

**Comment by bebo-dot-dev** [comment] 2022-05-05 07:14
Hi @rasogi I don't know if you made any progress but I thought I'd update this issue with a comment to note that a change has been applied to introduce support for Python3.

Closing.

**Closed as completed by bebo-dot-dev** 2022-05-05 07:14 UTC
Labels: question
